# Generated by Django 4.2.1 on 2023-05-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True, verbose_name='CV Language')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status deletion')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'CV Language',
                'verbose_name_plural': 'CV Languages',
                'db_table': 'cv_languages',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('isSuperAdmin', models.BooleanField(default=False, verbose_name='Super admin')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('host', models.CharField(max_length=100, verbose_name='Host access')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.module', verbose_name='Module_id')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.role', verbose_name='Role_id')),
            ],
            options={
                'verbose_name': 'Role_Module',
                'verbose_name_plural': 'Role_Modules',
                'db_table': 'role_module',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='module',
            field=models.ManyToManyField(through='general.RoleModule', to='general.module'),
        ),
    ]
